services:
  frontend:
    build: mern/frontend
    ports:
      - "5173:5173"
    networks:
      - mern
  backend:
    build: mern/backend 
    ports:
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - mongo
    ports:
      - "2707:2707"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db
networks:
  mern:
    driver: bridge
voulmes:
  mongo-data:
    driver: local